### PR TITLE
Feature: Posts feed 

### PR DESCRIPTION
**Pull request by prakartigoel24**
**Description**

This PR introduces a new feature called Posts feed, which is a type of 'channel' for posting content with image or pdfs, the feed for member posts. 

- A user can create new posts and edit or delete them.
- A user can like a post.
- A used can comment on posts and edit or delete their comment. 
- Post owner can delete others comments on their post.
- Admins and moderators can delete anyone's post.

**Type of Change**

* Check one or more boxes that apply:

    - [x] New feature
  

**Changes Made:**
- Changes can be tracked by commits.

**Screenshots or Screen Recording (if applicable):**

https://github.com/Univibe-majorproject/UniVibe/assets/65300982/b376addd-1818-48de-9c64-f0a3ac98708f

### CODE REVIEW

**Comment by SuperiorSam22** [comment]
@prakartigoel24 
- Post's UI breaks on uploading images, comments cannot be added below that, that box is inaccessible.
  (images added in feed 1 and 2) 
- Send message button is in the middle of the comment box it overlaps the texts underneath.  
- When comment is in edit mode Enter key moves the cursor to the next line instead of saving it, Escape works fine. 
- rest everything seems to be working fine 

    Feed UI looks pretty...nicely done

**Comment by SuperiorSam22** [comment]
@prakartigoel24 - I don't know if you asked the commit review again or not but it popped a notification for review. Anyways this is for commit -  [887f603]. I'm gonna approve the review. Raise another review  request when you need it. 
image

**Review by SuperiorSam22 — COMMENTED** [review]
All good! refer previous comment

**Comment by prakartigoel24** [comment]
> @prakartigoel24 - I don't know if you asked the commit review again or not but it popped a notification for review. Anyways this is for commit - [[887f603](https://github.com/Univibe-majorproject/UniVibe/commit/887f60311a8616b06bf058114251c352f12723ab)]. I'm gonna approve the review. Raise another review request when you need it. image

Enter to save the edited comment will not work because it is a text area and not an input. We don't need to fix that. Also, the unsaved comment will stay in the edit comment box as a draft.

**Comment by SuperiorSam22** [comment]
> > @prakartigoel24 - I don't know if you asked the commit review again or not but it popped a notification for review. Anyways this is for commit - [[887f603](https://github.com/Univibe-majorproject/UniVibe/commit/887f60311a8616b06bf058114251c352f12723ab)]. I'm gonna approve the review. Raise another review request when you need it. image
> 
> Enter to save the edited comment will not work because it is a text area and not an input. We don't need to fix that. Also, the unsaved comment will stay in the edit comment box as a draft.

@prakartigoel24 ok, then remove the text 'enter to save' from text area, because escape to cancel works.

**Comment by SuperiorSam22** [comment]
@prakartigoel24 
- Other functions are working but the comment box UI breaks on exceeding a certain word limit. 
- Afterwards it cannot be edited or deleted. 
- Maybe limit the amount of characters on the comment box or expand the comment box to accommodate the text. 
image

**Comment by prakartigoel24** [comment]
> @prakartigoel24
> 
> * Other functions are working but the comment box UI breaks on exceeding a certain word limit.
> * Afterwards it cannot be edited or deleted.
> * Maybe limit the amount of characters on the comment box or expand the comment box to accommodate the text.
>   image

Fixed the text overflow problem and also added limits to both comments and posts.

**Review by SuperiorSam22 — APPROVED** [review]
All good!

**Pull request merged**
