### PR TITLE
Changed the Dark theme to purple-neon

### PR DESCRIPTION
**Pull request by prakartigoel24**
**Description**

Changed the dark theme of the application to purple-neon theme. 

**Type of Change**

* Check one or more boxes that apply:
    - [X] Improvement

**Include any relevant screenshots or images to showcase the changes.**
image

**Additional Information**

* Might have to check every feature we merged with theme. Since i merged theme into this branch and resolved a lot of merge conflicts.

### CODE REVIEW

**Comment by prakartigoel24** [comment]
@SuperiorSam22 check different features which we merged with theme in previous 4-5 PRs.

**Comment by SuperiorSam22** [comment]
> @SuperiorSam22 check different features which we merged with theme in previous 4-5 PRs.

@prakartigoel24 okie

**Comment by prakartigoel24** [comment]
> > @SuperiorSam22 check different features which we merged with theme in previous 4-5 PRs.
> 
> @prakartigoel24 okie

Hey did you check the features?

**Comment by SuperiorSam22** [comment]
> > > @SuperiorSam22 check different features which we merged with theme in previous 4-5 PRs.
> > 
> > 
> > @prakartigoel24 okie
> 
> Hey did you check the features?

@prakartigoel24 yes

**Review by SuperiorSam22 — APPROVED** [review]
All good!

**Pull request merged**
