### PR TITLE
Feat : Additional User Profile Options 

### PR DESCRIPTION
**Pull request by prakartigoel24**
**Description**
This PR adds more details in the UserProfile which opens when the user clicks : `UserButton` -> `Manage Account` -> `More details (in side navbar)` .

**Type of Change**

* Check one or more boxes that apply:
    - [X] New feature

**Changes Made:**
Added **"more details"** option in the **UserProfile** modal which is used to update additional information about the user in the "**unsafeMetadata**" option of the "**user**" object provided by Clerk. 

**The following additional user detail options are added :**  

- profileBio,
- collegeName,
- course,
- branch,
- batch,
- dob
- socialProfiles - linkedin and github
- skills

**Screenshots or Screen Recording (if applicable):**
image

**Additional Information**
We need to enable webhooks to sync our database with the clerk data so that whenever a user updates their profile information through the UserButton, it also gets updated in our database.

### CODE REVIEW

**Comment by prakartigoel24** [comment]
@SuperiorSam22 hey, you have to improve the UI of this "more details" page .

**Comment by SuperiorSam22** [comment]
@prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.

**Comment by prakartigoel24** [comment]
> @prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.

Hey i fixed that issue, check once more for any other issues.

**Comment by SuperiorSam22** [comment]
> > @prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.
> 
> Hey i fixed that issue, check once more for any other issues.
@prakartigoel24 Its working fine now. Error message is displayed below the input field.
 Also can you change one thing? Like after the user saves the changes it should not reload the entire application.
like remove `window.location.reload();` from line 123 and add `<Button onClick={() => setIsEditing(true)}>Edit</Button>` after line 452. Can we do it in this way?

**Comment by prakartigoel24** [comment]
> > > @prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.
> > 
> > 
> > Hey i fixed that issue, check once more for any other issues.
> > @prakartigoel24 Its working fine now. Error message is displayed below the input field.
> > Also can you change one thing? Like after the user saves the changes it should not reload the entire application.
> > like remove `window.location.reload();` from line 123 and add `<Button onClick={() => setIsEditing(true)}>Edit</Button>` after line 452. Can we do it in this way?

Adding onClick to our Button breaks the form somehow since form submit is done by `onSubmit={form.handleSubmit(onSubmit)}` . Also if we remove the window.location.reload() then the UserProfile Modal for "more-details" will get stuck on the 'Details Saved!'. Router.refrest() is not working, already checked.

**Comment by SuperiorSam22** [comment]
> > > > @prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.
> > > 
> > > 
> > > Hey i fixed that issue, check once more for any other issues.
> > > @prakartigoel24 Its working fine now. Error message is displayed below the input field.
> > > Also can you change one thing? Like after the user saves the changes it should not reload the entire application.
> > > like remove `window.location.reload();` from line 123 and add `<Button onClick={() => setIsEditing(true)}>Edit</Button>` after line 452. Can we do it in this way?
> 
> Adding onClick to our Button breaks the form somehow since form submit is done by `onSubmit={form.handleSubmit(onSubmit)}` . Also if we remove the window.location.reload() then the UserProfile Modal for "more-details" will get stuck on the 'Details Saved!'. Router.refrest() is not working, already checked.

@prakartigoel24 how is it breaking the form? it seems to be working, the details in the form is being saved. And yes without the reload that modal is stuck at "Details Saved" but that edit button is taking the user back to the edit modal page.

**Comment by prakartigoel24** [comment]
> > > > > @prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.
> > > > 
> > > > 
> > > > Hey i fixed that issue, check once more for any other issues.
> > > > @prakartigoel24 Its working fine now. Error message is displayed below the input field.
> > > > Also can you change one thing? Like after the user saves the changes it should not reload the entire application.
> > > > like remove `window.location.reload();` from line 123 and add `<Button onClick={() => setIsEditing(true)}>Edit</Button>` after line 452. Can we do it in this way?
> > 
> > 
> > Adding onClick to our Button breaks the form somehow since form submit is done by `onSubmit={form.handleSubmit(onSubmit)}` . Also if we remove the window.location.reload() then the UserProfile Modal for "more-details" will get stuck on the 'Details Saved!'. Router.refrest() is not working, already checked.
> 
> @prakartigoel24 how is it breaking the form? it seems to be working, the details in the form is being saved. And yes without the reload that modal is stuck at "Details Saved" but that edit button is taking the user back to the edit modal page.

Try to add onClick to the Button and then fill invalid form input like more than 10 skills or maybe leave out the college name, then click on save, you will not see the error messages on the screen. (This is when `<Button onClick={() => setIsEditing(false)}>Edit</Button>`  is used. Also the details are not being saved in the unsafeMetadata, only the UI is showing details saved. 

Image for your reference: 
image

**Comment by SuperiorSam22** [comment]
> > > > > > @prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.
> > > > > 
> > > > > 
> > > > > Hey i fixed that issue, check once more for any other issues.
> > > > > @prakartigoel24 Its working fine now. Error message is displayed below the input field.
> > > > > Also can you change one thing? Like after the user saves the changes it should not reload the entire application.
> > > > > like remove `window.location.reload();` from line 123 and add `<Button onClick={() => setIsEditing(true)}>Edit</Button>` after line 452. Can we do it in this way?
> > > 
> > > 
> > > Adding onClick to our Button breaks the form somehow since form submit is done by `onSubmit={form.handleSubmit(onSubmit)}` . Also if we remove the window.location.reload() then the UserProfile Modal for "more-details" will get stuck on the 'Details Saved!'. Router.refrest() is not working, already checked.
> > 
> > 
> > @prakartigoel24 how is it breaking the form? it seems to be working, the details in the form is being saved. And yes without the reload that modal is stuck at "Details Saved" but that edit button is taking the user back to the edit modal page.
> 
> Try to add onClick to the Button and then fill invalid form input like more than 10 skills or maybe leave out the college name, then click on save, you will not see the error messages on the screen. (This is when `<Button onClick={() => setIsEditing(false)}>Edit</Button>` is used. Also the details are not being saved in the unsafeMetadata, only the UI is showing details saved.
> 
> Image for your reference: image

@prakartigoel24 You don't have to add onClick on the "Save" Button. `<Button onClick={() => setIsEditing(true)}>Edit</Button> ` add this after the `<h2>Details Saved!</h2> `. Check it once if its working and tell me. This will give you a edit button on the Details Saved page. Just check if metadata is being updated or not. Because when I tried it, I was not getting that Form submission cancel warning.

**Comment by prakartigoel24** [comment]
> > > > > > > @prakartigoel24 Error on filling more than 10 skills in userbutton. Its not popping on the modal but on the application UI.
> > > > > > 
> > > > > > 
> > > > > > Hey i fixed that issue, check once more for any other issues.
> > > > > > @prakartigoel24 Its working fine now. Error message is displayed below the input field.
> > > > > > Also can you change one thing? Like after the user saves the changes it should not reload the entire application.
> > > > > > like remove `window.location.reload();` from line 123 and add `<Button onClick={() => setIsEditing(true)}>Edit</Button>` after line 452. Can we do it in this way?
> > > > 
> > > > 
> > > > Adding onClick to our Button breaks the form somehow since form submit is done by `onSubmit={form.handleSubmit(onSubmit)}` . Also if we remove the window.location.reload() then the UserProfile Modal for "more-details" will get stuck on the 'Details Saved!'. Router.refrest() is not working, already checked.
> > > 
> > > 
> > > @prakartigoel24 how is it breaking the form? it seems to be working, the details in the form is being saved. And yes without the reload that modal is stuck at "Details Saved" but that edit button is taking the user back to the edit modal page.
> > 
> > 
> > Try to add onClick to the Button and then fill invalid form input like more than 10 skills or maybe leave out the college name, then click on save, you will not see the error messages on the screen. (This is when `<Button onClick={() => setIsEditing(false)}>Edit</Button>` is used. Also the details are not being saved in the unsafeMetadata, only the UI is showing details saved.
> > Image for your reference: image
> 
> @prakartigoel24 You don't have to add onClick on the "Save" Button. `<Button onClick={() => setIsEditing(true)}>Edit</Button> ` add this after the `<h2>Details Saved!</h2> `. Check it once if its working and tell me. This will give you a edit button on the Details Saved page. Just check if metadata is being updated or not. Because when I tried it, I was not getting that Form submission cancel warning.

This seems to be working fine, the unsafeMetadata us being updated. Removed the page reload.

**Comment by prakartigoel24** [comment]
@SuperiorSam22  check once again and if you find any more issues, let me know.

**Review by SuperiorSam22 — APPROVED** [review]
All good, everything's working fine.

**Pull request merged**
