### PR TITLE
Fix: #22 Server name and channel name length limit not set 

### LINKED ISSUE #22: [BUG]: Server name and channel name length limit not set
## Bug Report

**Describe the bug**
When creating a server or a channel with a name containing more than 15-20 characters, it goes out of the server-sidebar component. Subsequently hiding the server settings dropdown and also the edit and delete options for channels.

**To Reproduce**
1. Sign in using google to an account.
2. Create a new server and give server name of more than 15-20 characters.
3. You will be redirected to the server's page.
4. In the sidebar you will see that the server name goes out of the boundary of server-sidebar inside a server-header  and also the server settings dropdown is not visible.
5. Now click on plus (+) button in the channels list to create a new channel.
6. Give the channel name of more than 15-20 characters and any type.
7. You will see the channel name getting cut off and also the edit and delete options are hidden and not visible on hovering over the channel name.

**Expected Behavior:**
 - Server name should get truncated and not go outside the server-sidebar and server-header so that the server settings dropdown is visible.
 - Channel name should get truncated to fit the sidebar and also the edit and delete channel options should be visible on hovering over the channel name in the channels list. 

**Screenshots**
## Bug image 
image

## Original behavior 
image

### PR DESCRIPTION
**Pull request by prakartigoel24**
**Description**
This PR fixes #22 by fixing the width of the server name and channel name containers and truncating the overflowing text.

**Related Issues**
 Fixes #22 

**Type of Change**

* Check one or more boxes that apply:
    - [X] Bug fix
    
**Changes Made:**
 - Set the width of divs containing the channels and members to w-52. (In file **'components\server\server-sidebar.jsx'**).
 - Added **truncate** property to `<p>{channel.name}</p>` to prevent channel names from overflowing the container. (In file **'components\server\server-channel.jsx'**
 - Converted the 'server.name' to a `<p>{server.name}</p>` tag and added the **truncate** property to prevent the server name from overflowing its button container. (In file **'components\server\server-header.jsx'**).
 -  Added **truncate** property to `<p>{member.profile.name}</p>` to prevent member names from overflowing the container. (In file **'components\server\server-member.jsx'**).
 - Added **w-56** and **truncate** to`<p>{name}</p>` in **'chat-header.jsx'**.
 - Added max limit of 25 characters to channel name in form schema. (In **create-channel-modal.jsx** and **edit-channel-modal.jsx**).

**Screenshots or Screen Recording (if applicable):**
image

### CODE REVIEW

**Comment by prakartigoel24** [comment]
@SuperiorSam22 do we require a limit on the server name as well ? Since college names can be very long and we are already truncating the server name in the server-header.

**Comment by SuperiorSam22** [comment]
@prakartigoel24 Yes, limit the server name, maybe from 50 - 80 characters.

**Comment by prakartigoel24** [comment]
> @prakartigoel24 Yes, limit the server name, maybe from 50 - 80 characters.

What is the use of limiting if its 50-80 characters?

**Comment by SuperiorSam22** [comment]
> > @prakartigoel24 Yes, limit the server name, maybe from 50 - 80 characters.
> 
> What is the use of limiting if its 50-80 characters?

I've checked it. After a certain limit of characters the server create button does not work. And if we implement hover to show the entire server or channel name then displaying a large number of characters will look horrible, if the user somehow exceeds a large amount of characters (maybe 1000). 
It will also break some other UI that displays the server name or channel name. Like when we display the server name while deleting the server or deleting a channel.

**Comment by prakartigoel24** [comment]
> > > @prakartigoel24 Yes, limit the server name, maybe from 50 - 80 characters.
> > 
> > 
> > What is the use of limiting if its 50-80 characters?
> 
> I've checked it. After a certain limit of characters the server create button does not work. And if we implement hover to show the entire server or channel name then displaying a large number of characters will look horrible, if the user somehow exceeds a large amount of characters (maybe 1000). It will also break some other UI that displays the server name or channel name. Like when we display the server name while deleting the server or deleting a channel.

Okay that makes sense. I will limit the server name to 60 characters then.

**Comment by SuperiorSam22** [comment]
> > > > @prakartigoel24 Yes, limit the server name, maybe from 50 - 80 characters.
> > > 
> > > 
> > > What is the use of limiting if its 50-80 characters?
> > 
> > 
> > I've checked it. After a certain limit of characters the server create button does not work. And if we implement hover to show the entire server or channel name then displaying a large number of characters will look horrible, if the user somehow exceeds a large amount of characters (maybe 1000). It will also break some other UI that displays the server name or channel name. Like when we display the server name while deleting the server or deleting a channel.
> 
> Okay that makes sense. I will limit the server name to 60 characters then.

okay..

**Pull request merged**
